### ISSUE TITLE
Fix the variables fetched from the data endpoint.

### ISSUE THREAD

**Issue by Lakhwinderr** [Lakhwinderr/Open-Source-Discovery#1]
The data is returned as an array of objects. Identify the correct data variable for the repository URL and number of stars. Change the react code accordingly. 
![image](https://github.com/user-attachments/assets/3c2bc7cd-8a87-4cfd-978f-31a84c2c09aa)

**Comment by MuhammedJaseemVK** [comment]
Hi @Lakhwinderr . Please assign this to me. I would like to work on this

**Comment by Lakhwinderr** [comment]
HI @MuhammedJaseemVK,
Thanks for your interest in contributing! You can check out our CONTRIBUTING.md for guidelines on how to write a pull request (PR). Since this involves updating the React code, feel free to include screenshots or images to demonstrate your changes effectively.

If you have any questions, don’t hesitate to ask!
Looking forward to your contribution!
