### ISSUE TITLE
Fix Star Button Functionality for Starred Repos

### ISSUE THREAD

**Issue by Lakhwinderr** [Lakhwinderr/Open-Source-Discovery#2]
Our app currently has an issue where starred repositories are not marked as starred once the star button is hit. Instead, the app re-renders and updates the `searchResults` array again, causing the starred status to reset.  

To resolve this issue, please consider creating a new state variable to manage the starred status or fix the existing code to ensure that the starred repos retain their state after the star button is clicked.

**Comment by Zish303** [comment]
@Lakhwinderr Please assign me this issue.

**Comment by Lakhwinderr** [comment]
@Zish303 I assigned it to you. You can implement [memo](https://react.dev/reference/react/memo) and [useMemo](https://react.dev/reference/react/useMemo) in React Components to optimize the code.

**Comment by Zish303** [comment]
@Lakhwinderr I can't reporoduce this bug. Star button functionality works fine for me.
Can you share some screenshot where this bug is shown.

**Comment by Lakhwinderr** [comment]
@Zish303 I am fixing some of the basic errors, and creating separate components. I will notify you soon what to work on. Till then you can add the put request endpoint to delete the repo from the database. For now, we can save the repo.  Another endpoint is missing to update the repository array for the user.  When we hit the star button marked as star, it should delete that repo from the user's array.

**Comment by Lakhwinderr** [comment]
@Zish303  When we click on the star of any container, it must be in a starred condition, which means a highlighted star. It just flickers for a second and disappears in the second render. Try to reproduce the bug and let me know if you understand the issue. Please fetch the new changes.
![image](https://github.com/user-attachments/assets/7cdf168b-2749-43c3-9719-cf4e63dfeb78)

**Comment by Zish303** [comment]
Now I can reproduce the bug. I will start working on it.

**Comment by Lakhwinderr** [comment]
Issue solved .
