### ISSUE TITLE
Star Functionality in the My Account Page

### ISSUE THREAD

**Issue by Lakhwinderr** [Lakhwinderr/Open-Source-Discovery#9]
Users can currently add or remove repositories from their search results by starring or un-starring them. We’d like to provide this same functionality for repositories in the My Account tab.

**Comment by AliWayDev** [comment]
Do you mean the search functionality for starred list repos in my account tab?

**Comment by AliWayDev** [comment]
> Do you mean the search functionality for starred list repos in my account tab?

If it is, please assign it to me.

**Comment by AliWayDev** [comment]
Assign it to me, please.

**Comment by AliWayDev** [comment]
I guess you can close this issue.
